// Generated by `steelyard init`. You own this file — edit freely.
// To regenerate after manifest changes, run `steelyard init` again.
import { createCommerceRoutes, resolveManifestModule } from "@steelyard/next";
import manifestModule from "@/commerce";

const routes = createCommerceRoutes(await resolveManifestModule(manifestModule));

export const GET = routes.acpFeed;
