// Copyright (c) Steelyard contributors. MIT License.
//
// createCommerceRoutes — bundles the four Steelyard read surfaces into Next-shaped
// handlers. Each route.ts file generated by the CLI imports the manifest and one
// of these handlers, so route files stay at 3 lines.

import { createAcpFeedHandler } from "@steelyard-dev/protocol/acp";
import { createCommerceManifestHandler } from "@steelyard-dev/protocol/commerce-manifest";
import { createMcpHttpHandler, type McpHttpHandlerOptions } from "@steelyard-dev/protocol/mcp";
import { createUcpHandler, type UcpHandlerOptions } from "@steelyard-dev/protocol/ucp";
import type { CommerceManifestPeer, Manifest, PeerName } from "@steelyard-dev/core";
import { toNextHandler, type NextRouteHandler } from "./to-next-handler.js";

export interface CreateCommerceRoutesOptions {
  publicOrigin?: string;
  peers?: Partial<Record<PeerName, CommerceManifestPeer>>;
  generatedAt?: string;
  mcp?: McpHttpHandlerOptions;
  ucp?: UcpHandlerOptions;
}

export interface CommerceRoutes {
  wellKnown: NextRouteHandler;
  mcp: NextRouteHandler;
  acpFeed: NextRouteHandler;
  ucp: NextRouteHandler;
}

export function createCommerceRoutes(
  manifest: Manifest,
  opts: CreateCommerceRoutesOptions = {}
): CommerceRoutes {
  const wellKnown = createCommerceManifestHandler(manifest, {
    peers: opts.peers,
    generatedAt: opts.generatedAt
  });
  const mcp = createMcpHttpHandler(manifest, opts.mcp ?? {});
  const acp = createAcpFeedHandler(manifest);
  const ucp = createUcpHandler(manifest, opts.ucp ?? {});

  return {
    wellKnown: toNextHandler(wellKnown),
    mcp: toNextHandler(mcp),
    acpFeed: toNextHandler(acp),
    ucp: toNextHandler(ucp)
  };
}
