// Generated by `steelyard init`. You own this file — edit freely.
// To regenerate after manifest changes, run `steelyard init` again.
// UCP catalog endpoints — /api/catalog/search, /api/catalog/lookup, /api/catalog/product.
// The catch-all forwards to the same handler that serves /.well-known/ucp; the
// handler internally routes by request URL.

import { createCommerceRoutes, resolveManifestModule } from "steelyard/next";
import manifestModule from "@/commerce";

const routes = createCommerceRoutes(await resolveManifestModule(manifestModule));

export const GET = routes.ucp;
export const POST = routes.ucp;
