// Generated by `steelyard init`. You own this file — edit freely.
// To regenerate after manifest changes, run `steelyard init` again.
// UCP discovery document — served at /.well-known/ucp.

import { createCommerceRoutes, resolveManifestModule } from "@steelyard/next";
import manifestModule from "@/commerce";

const routes = createCommerceRoutes(await resolveManifestModule(manifestModule));

export const GET = routes.ucp;
export const POST = routes.ucp;
