// Copyright (c) Steelyard contributors. MIT License.
//
// String templates for files written by `steelyard init`. Each function returns
// a complete file body. No EJS/handlebars — explicit template literals are
// shorter and easier to audit.

import type { Manifest } from "@steelyard/core";

export interface RouteTemplateOptions {
  manifestImport: string;
}

const HEADER = `// Generated by \`steelyard init\`. You own this file — edit freely.
// To regenerate after manifest changes, run \`steelyard init\` again.
`;

export function renderWellKnownRoute(opts: RouteTemplateOptions): string {
  return `${HEADER}import { createCommerceRoutes } from "@steelyard/next";
import manifestModule from "${opts.manifestImport}";

const routes = createCommerceRoutes(
  await resolve(manifestModule)
);

export const GET = routes.wellKnown;

async function resolve(m: unknown) {
  const value = (m as { default: unknown }).default;
  return typeof value === "function" ? await (value as () => Promise<unknown>)() : value;
}
`;
}

export function renderMcpRoute(opts: RouteTemplateOptions): string {
  return `${HEADER}import { createCommerceRoutes } from "@steelyard/next";
import manifestModule from "${opts.manifestImport}";

const routes = createCommerceRoutes(
  await resolve(manifestModule)
);

export const GET = routes.mcp;
export const POST = routes.mcp;

async function resolve(m: unknown) {
  const value = (m as { default: unknown }).default;
  return typeof value === "function" ? await (value as () => Promise<unknown>)() : value;
}
`;
}

export function renderAcpFeedRoute(opts: RouteTemplateOptions): string {
  return `${HEADER}import { createCommerceRoutes } from "@steelyard/next";
import manifestModule from "${opts.manifestImport}";

const routes = createCommerceRoutes(
  await resolve(manifestModule)
);

export const GET = routes.acpFeed;

async function resolve(m: unknown) {
  const value = (m as { default: unknown }).default;
  return typeof value === "function" ? await (value as () => Promise<unknown>)() : value;
}
`;
}

export function renderUcpRoute(opts: RouteTemplateOptions): string {
  return `${HEADER}// Catch-all for /.well-known/ucp and /api/catalog/* — UCP discovery + catalog.
// Path segment is named [...path] by convention.

import { createCommerceRoutes } from "@steelyard/next";
import manifestModule from "${opts.manifestImport}";

const routes = createCommerceRoutes(
  await resolve(manifestModule)
);

export const GET = routes.ucp;
export const POST = routes.ucp;

async function resolve(m: unknown) {
  const value = (m as { default: unknown }).default;
  return typeof value === "function" ? await (value as () => Promise<unknown>)() : value;
}
`;
}

export function renderManifestStub(seed: {
  identity: Manifest["identity"];
  offers: Manifest["catalog"]["offers"];
}): string {
  const body = JSON.stringify(seed, null, 2)
    .replace(/^/gm, "  ")
    .trim();
  return `// Steelyard commerce manifest — edit this file as your catalog evolves.
//
// Runs in Next.js dev mode with HMR: edit and refresh; the manifest is
// re-imported on next request.

import { defineCommerce } from "steelyard";

export default defineCommerce(${body});
`;
}

export function renderEnvLocalAddition(tier: "a" | "b"): string {
  if (tier === "a") return "";
  return `\n# Added by \`steelyard init\` — required for tier-B agent checkout.\nSTRIPE_SECRET_KEY=sk_test_replace_me\n`;
}

export interface RouteSpec {
  path: string;
  contents: string;
}

export function plannedRouteFiles(opts: RouteTemplateOptions): RouteSpec[] {
  return [
    { path: "app/.well-known/commerce.json/route.ts", contents: renderWellKnownRoute(opts) },
    { path: "app/mcp/route.ts", contents: renderMcpRoute(opts) },
    { path: "app/acp/feed/route.ts", contents: renderAcpFeedRoute(opts) },
    { path: "app/api/ucp/[...path]/route.ts", contents: renderUcpRoute(opts) }
  ];
}
